openapi: "3.0.2"
info:
  title: Auth API
  version: "1.0"
servers:
  - url: http://localhost:8000/v1
    description: Local development server
  - url: https://auth.up.railway.app/v1
    description: Remote development server
paths:
  /auth/google/login:
    get:
      description: ""
      tags: [auth]
      parameters: []
      responses:
        "200":
          description: OK
  /auth/user:
    get:
      description: ""
      tags: [auth]
      parameters: []
      responses:
        "200":
          description: OK
  /auth/status:
    get:
      description: ""
      tags: [auth]
      parameters: []
      responses:
        "200":
          description: OK
  /auth/logout:
    get:
      description: ""
      tags: [auth]
      parameters: []
      responses:
        "200":
          description: OK
  /auth/avatars/{avatarId}:
    get:
      description: ""
      tags: [auth]
      parameters:
        - name: avatarId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /users:
    get:
      description: "List all users with the given email."
      tags: [users]
      parameters:
        - name: email
          in: query
          description: "The email of the user to search for"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /users/{userId}:
    delete:
      description: "Delete a user"
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
  /users/{userId}/profile:
    get:
      description: ""
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    patch:
      description: ""
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                pronouns:
                  type: string
      responses:
        "200":
          description: OK
  /users/{userId}/roles:
    get:
      description: ""
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      description: ""
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domain:
                  type: string
                role:
                  type: string
      responses:
        "200":
          description: OK
    delete:
      description: ""
      tags: [users]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: domain
          in: query
          description: "The domain of the role to remove from the user."
          required: true
          schema:
            type: string
        - name: role
          in: query
          description: "The role to remove from the user."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /assignments:
    get:
      description: "List all assignments for a given email."
      tags: [assignments]
      parameters:
        - name: email
          in: query
          description: "The email to search for."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      description: "Create an assignment."
      tags: [assignments]
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      domain:
                        type: string
                      role:
                        type: string
      responses:
        "200":
          description: OK
  /assignments/{assignmentId}:
    patch:
      description: "Update an assignment by ID."
      tags: [assignments]
      parameters:
        - name: assignmentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      domain:
                        type: string
                      role:
                        type: string
      responses:
        "200":
          description: OK
    delete:
      description: "Delete an assignment by ID."
      tags: [assignments]
      parameters:
        - name: assignmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /domains:
    get:
      description: ""
      tags: [domains]
      parameters:
        - name: name
          in: query
          description: "The name of the domain to search for."
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      description: ""
      tags: [domains]
      parameters: []
      responses:
        "200":
          description: OK
  /domains/{domainId}:
    get:
      description: ""
      tags: [domains]
      parameters:
        - name: domainId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    patch:
      description: ""
      tags: [domains]
      parameters:
        - name: domainId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    delete:
      description: ""
      tags: [domains]
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /domains/{domainId}/roles:
    get:
      description: ""
      tags: [domains]
      parameters:
        - name: domainId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      description: ""
      tags: [domains]
      parameters:
        - name: domainId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    delete:
      description: ""
      tags: [domains]
      parameters:
        - name: domainId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
