version: '3.8'

services:
  app:
    container_name: codespace
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1-bullseye"
        NODE_VERSION: "18"
    command: sleep infinity
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      SERVER_PORT: "8000"
      MONGO_URI: "mongodb://db:27017/"
      DB_NAME: "auth"
      AUTH_ROOT_URL: "http://localhost:8000"
      COOKIE_DOMAIN: "localhost"
    volumes:
      - ..:/workspaces/auth:cached

  db:
    container_name: db
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

volumes:
  db-data:
